---
title: "R Notebook"
output: html_notebook
---

```{r}
#call library
library(igraph)
library(RColorBrewer)
library(visNetwork)
library(ggplot2)
library(tidyverse)
library(ggpubr)
#setwd("C:/Users/tinot/uu/human_network_lab_2")
#datainput
highschool_edge<-read.csv("Highschool_network_edge.csv",header=FALSE)
highschool_att<-read.csv("Highschool_network_att.csv",header = TRUE)
facebook_edge<-read.csv("Facebook_network_edge.csv",header=FALSE)
facebook_att<-read.csv("Facebook_network_att.csv",header = TRUE)
n=40
ER1 <- sample_gnp(n, 0.05, directed = FALSE, loops = FALSE)
ER2 <- sample_gnp(n, 0.1, directed = FALSE, loops = FALSE)
ER3 <- sample_gnp(n, 0.2, directed = FALSE, loops = FALSE)
ER1000 <- sample_gnp(1000, 0.2, directed = FALSE, loops= FALSE)
```

## Question 6

```{r}
n=40
ER1 <- sample_gnp(n, 0.05, directed = FALSE, loops = FALSE)
ER2 <- sample_gnp(n, 0.1, directed = FALSE, loops = FALSE)
ER3 <- sample_gnp(n, 0.2, directed = FALSE, loops = FALSE)
ER1000 <- sample_gnp(1000, 0.2, directed = FALSE, loops= FALSE)
#use only the largest component for analysis
#plot(ER1, layout = layout.circle(ER1), vertex.label = NA)
#plot(ER2, layout = layout.circle(ER2), vertex.label = NA)
#plot(ER3, layout = layout.circle(ER3), vertex.label = NA)
#plot(ER1000)
transitivity(ER1000)
```

## Question 7

Run the following code and discuss with your group mate how the rewiring probability changes the network structure:

```{r}
Regular<-watts.strogatz.game(dim=1,size=300,nei=6, p=0)
plot(Regular, layout=layout.circle, vertex.label=NA, vertex.size=5, 
main = "Network with zero rewiring probability ")

SW1 <- watts.strogatz.game(dim=1,size=300,nei=6, p=0.001)
plot(SW1, layout=layout.circle, vertex.label=NA, vertex.size=5, 
main= "Network with 0.001 rewiring probability ")

SW2 <-watts.strogatz.game(dim=1,size=300,nei=6, p=0.01)
plot(SW2, layout=layout.circle, vertex.label=NA, vertex.size=5, 
main = "Network with 0.01 rewiring probability ")

SW3 <- watts.strogatz.game(dim=1,size=300,nei=6, p=0.1)
plot(SW3, layout=layout.circle, vertex.label=NA, vertex.size=5, 
main = "Network with 0.1 rewiring probability ")

transitivity(Regular)
average.path.length(Regular)

transitivity(SW1)
average.path.length(SW1)
transitivity(SW2)
average.path.length(SW2)
transitivity(SW3)
average.path.length(SW3)
```

## Question 8

```{r}
shortest_paths <- distances(Regular, v = V(Regular), to = V(Regular))
L0 <- mean(shortest_paths[shortest_paths != Inf])
C0 <- transitivity(Regular)
vecC <- character()
vecL <- character()
vecP <- c(0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0,1, 0.5, 1)
for (val in vecP) {
network<-watts.strogatz.game(dim=1,size=300,nei=6, p=val)
shortest_paths <- distances(network, v = V(network), to = V(network))
L <- (mean(shortest_paths[shortest_paths != Inf]))/L0
C <- transitivity(network)/C0
vecL <- append(vecL, L)
vecC <- append(vecC, C)
}

vecL <- as.double(vecL)
vecC <- as.double(vecC)

data <- data.frame(vecL, vecC, vecP)
# Plot the data
ggplot(data) + 
  geom_point(aes(vecP, vecL)) + 
  geom_point(aes(vecP, vecC), colour='black', shape=0) +
  scale_x_log10() +
  labs(x = 'p', y = 'C and L') +
  geom_rect(mapping=aes(xmin=0.0004, xmax=0.012, ymin=0.3, ymax=1.02), color="red", alpha=0.00001) +
  theme_minimal()


```

```{r}
g0 <- barabasi.game(100, power = 0.5 , m = NULL, out.dist = NULL, out.seq = NULL, out.pref = FALSE, zero.appeal = 1, directed = FALSE,algorithm ="psumtree", start.graph = NULL) 

g1 <- barabasi.game(100, power = 1 , m = NULL, out.dist = NULL, out.seq = NULL, out.pref = FALSE, zero.appeal = 1, directed = FALSE,algorithm ="psumtree", start.graph = NULL) 

g1_5 <- barabasi.game(100, power = 1.5 , m = NULL, out.dist = NULL, out.seq = NULL, out.pref = FALSE, zero.appeal = 1, directed = FALSE,algorithm ="psumtree", start.graph = NULL) 

g2 <- barabasi.game(100, power = 2 , m = NULL, out.dist = NULL, out.seq = NULL, out.pref = FALSE, zero.appeal = 1, directed = FALSE,algorithm ="psumtree", start.graph = NULL) 

plot(g0, vertex.label= NA, edge.arrow.size=2.9, vertex.size = 4 ,layout = layout_nicely(g0), main = "Scale-free network model, power=0.5")

plot(g1, vertex.label= NA, edge.arrow.size=2.9, vertex.size = 4 ,layout = layout_nicely(g1), main = "Scale-free network model, power=1")

plot(g1_5, vertex.label= NA, edge.arrow.size=2.9, vertex.size = 4 ,layout = layout_nicely(g1_5), main = "Scale-free network model, power=1.5")

plot(g2, vertex.label= NA, edge.arrow.size=2.9, vertex.size = 4 ,layout = layout_nicely(g2), main = "Scale-free network model, power=2")

```

# Question 9

```{r}
library(igraph)
set.seed(100)
random_n <- sample(1:100, 1)
subset_random_05 <- igraph::delete.vertices(g0, V(g0) ==  random_n)
subset_random_15 <- igraph::delete.vertices(g1_5, V(g1_5) ==  random_n)

degree_FB <- degree(subset_random_05, mode = "all") %>% sort(T) 

node_with_max05 <- degree(g0) == max(degree(g0))
node_with_max15 <- max(degree(g1_5))

subset_target_05 <- igraph::delete.vertices(g0, V(g0) == match(max(degree(g0)), degree(g0)))
subset_target_15 <- igraph::delete.vertices(g1_5, V(g1_5) == match(max(degree(g1_5)), degree(g1_5)))


diameter(g0)
diameter(g1_5)

diameter(subset_random_05)
diameter(subset_random_15)

diameter(subset_target_05)
diameter(subset_target_15, unconnected = T)

count_components(subset_random_05)
count_components(subset_random_15)

count_components(subset_target_05)
count_components(subset_target_15)
```

```{r}


plot(subset_random_05, vertex.label= NA, edge.arrow.size=2.9,xlim = c(-1, 1), ylim = c(-1, 1) , vertex.size = 4 ,layout = layout_nicely(subset_random_05), xlab = "Random attack on network model, power=0.5")

plot(subset_random_15, vertex.label= NA, edge.arrow.size=2.9, vertex.size = 4 ,xlim = c(-1, 1), ylim = c(-1, 1),layout = layout_nicely(subset_random_15), xlab = "Random attack on network model, power=1.5")

plot(subset_target_05, vertex.label= NA, edge.arrow.size=2.9, vertex.size = 4 ,xlim = c(-1, 1), ylim = c(-1, 1),layout = layout_nicely(subset_target_05), xlab = "Target attack on network model, power=0.5")

plot(subset_target_15, vertex.label= NA, edge.arrow.size=2.9, vertex.size = 4 ,xlim = c(-1, 1), ylim = c(-1, 1),layout = layout_nicely(subset_target_15), xlab = "Target attack on network model, power=1.5")

```
