---
title: "assignment2"
author: "tino"
date: "2023-03-20"
output: html_document
---

```{r setup, include=FALSE}
#call library
library(igraph)
library(RColorBrewer)
library(visNetwork)
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(dplyr)
library("GGally") 
# setwd("C:/Users/tinot/uu/human_network_lab_2") # how to colaborate on this? NP, but just for the sake of comnveniesnc
#datainput
highschool_edge<-read.csv("Highschool_network_edge.csv",header=FALSE)
highschool_att<-read.csv("Highschool_network_att.csv",header = TRUE)
facebook_edge<-read.csv("Facebook_network_edge.csv",header=FALSE)
facebook_att<-read.csv("Facebook_network_att.csv",header = TRUE)
```

## Networks

```{r}
#build high school network
highschool_nodes<-data.frame(name=as.character(highschool_att$NodeID),
 gender=as.character(highschool_att$Gender),
 hall=as.character(highschool_att$Hall))
highschool_edges<-data.frame(from=c(as.character(highschool_edge[,1])),
 to=c(as.character(highschool_edge[,2])))
Highschool<-graph_from_data_frame(highschool_edges,directed = FALSE,vertices =
highschool_nodes)
co <- components(Highschool)
Highschool <- induced.subgraph(Highschool, which(co$membership == which.max(co$csize)))

#use only the largest component for analysis
summary(Highschool)

#build facebook network
facebook_nodes<-data.frame(name=as.character(facebook_att$NodeID))
facebook_edges<-data.frame(from=c(as.character(facebook_edge[,1])),
 to=c(as.character(facebook_edge[,2])))
Facebook<-graph_from_data_frame(facebook_edges,directed = FALSE,vertices = facebook_nodes)
summary(Facebook)
```

## Question 1

```{r Question1}
# Question 1
#function to calculate centrality metrics
degree_n = (degree(Highschool, mode = "all"))
closeness_n = (closeness(Highschool, normalized = TRUE))
betweenness_n = betweenness(Highschool, directed = FALSE, normalized = TRUE)
eigen_n = eigen_centrality(Highschool)

which.max(degree_n)
which.max(closeness_n)
which.max(betweenness_n)
which.max(eigen_n$vector)
#function to visualize the network (with interaction)
set.seed(100)
Highschool_interactive_layout<-visNetwork(data.frame(id=V(Highschool)$name),
                                          highschool_edges, main = "Highschool",submain="Can zoom in/out to check the IDs and
ties") %>%
  visIgraphLayout(layout = "layout_nicely",smooth = FALSE) %>%
  visNodes(shape="circle",label = TRUE) %>%
  visOptions(highlightNearest = list(enabled = T, hover = T), nodesIdSelection = T)
Highschool_interactive_layout
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Question 2

```{r Question2}
# Question 2
# Correlation High school network
ggplot() + 
  geom_point(aes(degree_n, betweenness_n)) + 
  geom_smooth(aes(degree_n, betweenness_n), method="lm") + 
  stat_cor(aes(degree_n, betweenness_n), method = "pearson")

ggplot() + 
  geom_point(aes(degree_n, closeness_n)) + 
  geom_smooth(aes(degree_n, closeness_n), method="lm") + 
  stat_cor(aes(degree_n, closeness_n), method = "pearson")

ggplot() + 
  geom_point(aes(degree_n, eigen_n$vector)) + 
  geom_smooth(aes(degree_n, eigen_n$vector), method="lm") + 
  stat_cor(aes(degree_n, eigen_n$vector), method = "pearson")

# Correlation Facebook network
degree_n_fb = (degree(Facebook, mode = "all"))
closeness_n_fb = (closeness(Facebook, normalized = TRUE))
betweenness_n_fb = betweenness(Facebook, directed = FALSE, normalized = TRUE)
eigen_n_fb = eigen_centrality(Facebook)

ggplot() + 
  geom_point(aes(degree_n_fb, betweenness_n_fb)) + 
  geom_smooth(aes(degree_n_fb, betweenness_n_fb), method="lm") + 
  stat_cor(aes(degree_n_fb, betweenness_n_fb), method = "pearson")

ggplot() + 
  geom_point(aes(degree_n_fb, closeness_n_fb)) + 
  geom_smooth(aes(degree_n_fb, closeness_n_fb), method="lm") + 
  stat_cor(aes(degree_n_fb, closeness_n_fb), method = "pearson")

ggplot() + 
  geom_point(aes(degree_n_fb, eigen_n_fb$vector)) + 
  geom_smooth(aes(degree_n_fb, eigen_n_fb$vector), method="lm") + 
  stat_cor(aes(degree_n_fb, eigen_n_fb$vector), method = "pearson")
```

## Question 3

```{r}
h_distance = 
  distances(
 Highschool,
 v = V(Highschool),
 to = V(Highschool),
 mode = c("all", "out", "in"),
 weights = NULL) 
#Shortest path lengths between every pair of two nodes in the high school network

fb_distance = 
  distances(
 Facebook,
 v = V(Facebook),
 to = V(Facebook),
 mode = c("all", "out", "in"),
 weights = NULL) 
#Shortest path lengths between every pair of two nodes in the Facebook network
```
### plots for Facebooks
```{r}
dd_facebook<- degree_distribution(Facebook)

# Convert degree distribution to data frame
degree_distribution <- data.frame(degree = seq(1:length(dd_facebook)), 
                                  frequency = dd_facebook)

probs = c(0.5, 0.9)
quantiles <- quantile(degree_FB, prob=probs)

# Plot degree distribution using ggplot2
ggplot(degree_distribution, aes(x = degree, y = frequency)) +
  geom_bar(stat = "identity") +
  xlab("Degree") +
  ylab("% of total count")+
  geom_vline(xintercept = quantiles[1], colour="red", linetype="dotdash") +
  geom_vline(xintercept = quantiles[2], colour="red", linetype="dotdash" ) +
  scale_y_continuous(labels = scales::percent)+
  geom_label(aes(x = quantiles[1], y = 0.025, label ="q: 0.5")) +
  geom_label(aes(x = quantiles[2], y = 0.025, label = "q: 0.9 ")) +
  labs(title = "Degree distribution")+
  theme_minimal()
```
```{r}
shortest_count <- as.data.frame(table(fb_distance)) 
shortest_count$fraction <-  shortest_count$Freq /sum(shortest_count$Freq) # sum by the number of shortest paths

quantiles <- quantile(fb_distance, prob=probs)

shortest_count %>%
  ggplot(aes(x = fb_distance, y = fraction))+
  geom_bar(stat = "identity") +
  geom_vline(xintercept = quantiles[1], colour="red", linetype="dotdash") +
  geom_vline(xintercept = quantiles[2], colour="red", linetype="dotdash" ) +
  geom_label(aes(x = quantiles[1], y = 0.025, label ="q: 0.5")) +
  geom_label(aes(x = quantiles[2], y = 0.025, label = "q: 0.9 ")) +
  scale_y_continuous(labels = scales::percent)+
  xlab("Shortest path length") +
  ylab("% of total count by group")+ 
  labs(title = "Shortest path distribution")+
  theme_minimal()
```
### plots for highschool distributions

```{r}
dd_highschool<- degree_distribution(Highschool)

# Convert degree distribution to data frame
degree_distribution <- data.frame(degree = seq(1:length(dd_highschool)), 
                                  frequency = dd_highschool) 

probs = c(0.5, 0.9)
quantiles <- quantile(degree_HS, prob=probs)

# Plot degree distribution using ggplot2
ggplot(degree_distribution, aes(x = degree, y = frequency)) +
  geom_bar(stat = "identity") +
  xlab("Degree") +
  ylab("% of total count")+
  geom_vline(xintercept = quantiles[1], colour="red", linetype="dotdash") +
  geom_vline(xintercept = quantiles[2], colour="red", linetype="dotdash" ) +
  scale_y_continuous(labels = scales::percent)+
  geom_label(aes(x = quantiles[1], y = 0.025, label ="q: 0.5")) +
  geom_label(aes(x = quantiles[2], y = 0.025, label = "q: 0.9 ")) +
  labs(title = "Degree distribution")+
  theme_minimal()
```

```{r}

shortest_count <- as.data.frame(table(h_distance)) 
shortest_count$fraction <-  shortest_count$Freq /sum(shortest_count$Freq) # sum by the number of shortest paths

quantiles <- quantile(h_distance, prob=probs)

shortest_count %>%
  ggplot(aes(x = h_distance, y = fraction))+
  geom_bar(stat = "identity") +
  geom_vline(xintercept = quantiles[1], colour="red", linetype="dotdash") +
  geom_vline(xintercept = quantiles[2], colour="red", linetype="dotdash" ) +
  geom_label(aes(x = quantiles[1], y = 0.025, label ="q: 0.5")) +
  geom_label(aes(x = quantiles[2], y = 0.025, label = "q: 0.9 ")) +
  scale_y_continuous(labels = scales::percent)+
  xlab("Shortest path length") +
  ylab("% of total count by group")+ 
  labs(title = "Shortest path distribution high school")+
  theme_minimal()

```
## Question 4

```{r}
#Codes to visualize the network and calculate subgraph density:
## visualize the network by gender###
library(RColorBrewer)

coul <- brewer.pal(length(unique( V(Highschool)$gender)), "Set2")
my_color <- coul[as.numeric(as.factor(V(Highschool)$gender))]

set.seed(10)
plot(Highschool, vertex.color = my_color,
 vertex.size=5,
 layout=layout.fruchterman.reingold(Highschool),vertex.label=NA,
 main="Highschool network by gender")
 legend("bottomleft", legend=levels(as.factor(V(Highschool)$gender)) ,col = coul,
 bty = "n", pch=20 , pt.cex = 1.5, cex = 1.5, horiz = FALSE, inset = c(0.1, 0.1))

#introduce subgraph by gender, calculate their edge densities
group_gender <- as.factor(unique(V(Highschool)$gender))
sapply(levels(group_gender), function(x) {
 y <- induced_subgraph(Highschool, which(V(Highschool)$gender==x))
 cat(paste0("Density for ", x, " friends is ", edge_density(y), '\n'))
})


#introduce subgraph by gender, calculate their edge densities
group_hall <- as.factor(unique(V(Highschool)$hall))
sapply(levels(group_hall), function(x) {
 y <- induced_subgraph(Highschool, which(V(Highschool)$hall==x))
 cat(paste0("Density for ", x, " friends is ", edge_density(y), '\n'))
})

paste0('Density for the whole network is ', edge_density(Highschool))
unknown = induced_subgraph(Highschool, V(Highschool)$gender=='unknown')

Highschool_interactive_layout<-visNetwork(data.frame(id=V(unknown)$name),
                                          highschool_edges, main = "Highschool",submain="Can zoom in/out to check the IDs and
ties") %>%
  visIgraphLayout(layout = "layout_nicely",smooth = FALSE) %>%
  visNodes(shape="circle",label = TRUE) %>%
  visOptions(highlightNearest = list(enabled = T, hover = T), nodesIdSelection = T)
Highschool_interactive_layout
```

## Question 5

```{r}
#Codes to customize community and calculate modularity:
### customize community by gender ###
genderCommunity<-V(Highschool)$gender
genderCommunity<-replace(genderCommunity,genderCommunity=="female",1)
genderCommunity<-replace(genderCommunity,genderCommunity=="male",2)
genderCommunity<-replace(genderCommunity,genderCommunity=="unknown",3)
genderCommunity<-as.numeric(genderCommunity)

hallCommunity<-V(Highschool)$hall
hallCommunity<-replace(hallCommunity,hallCommunity=="1501",1)
hallCommunity<-replace(hallCommunity,hallCommunity=="1502",2)
hallCommunity<-replace(hallCommunity,hallCommunity=="1503",3)
hallCommunity<-replace(hallCommunity,hallCommunity=="1504",4)
hallCommunity<-replace(hallCommunity,hallCommunity=="1505",5)
hallCommunity<-as.numeric(hallCommunity)

#clustering
gender.clustering <- make_clusters(Highschool, membership=genderCommunity)
hall.clustering <- make_clusters(Highschool, membership=hallCommunity)

#modularity
paste0('gender modularity ', modularity(gender.clustering))
paste0('hall modularity ', modularity(hall.clustering))

### Louvain algorithm ###
Louv<-cluster_louvain(Highschool)
modularity(Louv)

```
